#!/bin/sh

# Check for the existence of Docker
if ! type docker > /dev/null 2>&1; then
	echo "# Docker not installed or not in PATH"
	echo "Skipping PlantUML generation"
	exit 0
fi

exec 1>&2

# Get all .dsl files from the list of staged files as a flattened, quoted string
staged=$(git diff-index --cached HEAD --name-only | grep '\.dsl$' | sed -e 's/^/"source\//' -e 's/$/" /' | tr -d '\n')

if [ -z "$staged" ];
then
	exit 0
else
	echo "Staged .dsl files:"
	echo $staged

	generatePlantUml="docker run --rm -v $(pwd)/dsl/poas:/usr/local/structurizr structurizr/cli export -workspace /usr/local/structurizr/workspace.dsl -format plantuml"
	eval $generatePlantUml

	generateMMD="docker run --rm -v $(pwd)/dsl/poas:/usr/local/structurizr structurizr/cli export -workspace /usr/local/structurizr/workspace.dsl -format mermaid"
	eval $generateMMD

	rm $(pwd)/dsl/poas/*-key*

	for filepath in $(pwd)/dsl/poas/*.puml; do
		[ -f "$filepath" ] || break
		# Generate diagrams for the staged .puml files
		generatePNG="docker run -v $(pwd)/dsl/poas:/data --rm -i dstockhammer/plantuml $(basename "$filepath")"
		eval $generatePNG
	done

	rm $(pwd)/dsl/poas/*.puml

	# Add generated diagrams to the commit
	git add dsl/poas

	exit 0
fi
