# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/awslabs/git-secrets
    rev: main
    hooks:
    - id: git-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.4
    hooks:
    -   id: gitleaks
  - repo: local
    hooks:
    - id: pre-commit-hooks/structurizr
      name: pre-commit-hooks/structurizr
      entry: pre-commit-hooks/structurizr
      language: system
