title: OPG technical guidance

permalink: pretty

defaults:
  - scope:
      path: "runbooks"
    values:
      runbook: true
  - scope:
      path: "standards"
    values:
      standard: true
  - scope:
      path: "guides"
    values:
      guide: true
  - scope:
      path: "principles"
    values:
      principle: true
  - scope:
      path: "adrs"
    values:
      principle: true
