name: "Run a specified report"
description: "Run a report (from opg-dora-metrics repo) and upload the artifact at the end to the workflow"

inputs:
  name:
    description: "Report name and name that will be used for the artifact"
  script:
    description: "Filepath of the python script to run"
  args:
    description: "Arguments to pass into the python script"
  output:
    description: "Directory to place the generated reports"
  workingdir:
    description: "Working directory to use"
  token:
    description: "Github token"
  # aws perms
  aws_access_key_id:
    description: "AWS access key id"
  aws_secret_access_key:
    description: "AWS_SECRET_ACCESS_KEY"
  aws_region:
    description: "region"

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ministryofjustice/opg-dora-metrics
        path: ${{ inputs.workingdir }}
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.workingdir }}
      run: |
        pip install -r requirements.txt
    - name: Configure AWS Credentials
      if: inputs.aws_access_key_id != ''
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: GitHubActionsTechDocs
    - name: "[${{ inputs.name }}] Generate report"
      shell: bash
      working-directory: ${{ inputs.workingdir }}
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.token }}
        LOG_LEVEL: ${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}
        SCRIPT: ${{ inputs.script }}
        ARGS: ${{ inputs.args }}
      run: |
        python ./${{ env.SCRIPT }} ${{ env.ARGS }}
        ls -lart ${{ inputs.output }}
    ## check out self to reset the config, but into a sub dir
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ github.repository }}
        path: opg_technical_guidance
    - name: "[${{ inputs.name }}] Upload artifact"
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.workingdir }}/${{ inputs.output }}/

