thirdparty = person "Third Party Software" "External API software interacting with a Lasting Power of Attorney."
attorney = person "Attorney" "Attorney interacting with a Lasting Power of Attorney."
donor = person "Donor" "Donor drafting the Lasting Power of Attorney."
certificateProvider = person "Certificate Provider" "Certificate Provider interacting with a Lasting Power of Attorney."
caseWorker = person "Case Worker" "Case worker."
organisation = person "Organisation" "Organisation or charity."
