graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [LPA Drafting Container - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    77("<div style='font-weight: bold'>Public LPA Support API</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Allows external companies to<br />add submit LPAs. [Owner:<br />Vega, Users: Modernising]</div>")
    style 77 fill:#438dd5,stroke:#2e6295,color:#ffffff
    1("<div style='font-weight: bold'>LPA UID Service</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Generates UIDs and stores<br />donor details.</div>")
    style 1 fill:#1168bd,stroke:#0b4884,color:#ffffff
    81("<div style='font-weight: bold'>LPA Paper Ingestion Service</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles the ingestion of the<br />Paper Journey and exposes<br />APIs for non valid OCR data<br />for caseworker keying.<br />[Owner: Modernising, Users:<br />Vega]</div>")
    style 81 fill:#438dd5,stroke:#2e6295,color:#ffffff
    51("<div style='font-weight: bold'>Case Management Public API</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Interaction point between<br />Case Management and other<br />services. [Owner: Vega,<br />Users: UaLPA, Modernising]</div>")
    style 51 fill:#999999,stroke:#6b6b6b,color:#ffffff
    52("<div style='font-weight: bold'>Registered LPA Service</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Highly available API for<br />reading and searching the LPA<br />Register. [Owner: Vega,<br />Users: UaLPA, Modernising]</div>")
    style 52 fill:#438dd5,stroke:#2e6295,color:#ffffff
    41["<div style='font-weight: bold'>Make a Lasting Power of Attorney Online</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Allows users to draft a<br />Lasting Power of Attorney<br />online. [Owner: Modernising,<br />Users: Vega]</div>"]
    style 41 fill:#1168bd,stroke:#0b4884,color:#ffffff

    subgraph 57 [LPA Drafting Container]
      style 57 fill:#ffffff,stroke:#2e6295,color:#2e6295

      58[("<div style='font-weight: bold'>Draft LPA Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores Draft LPA data.</div>")]
      style 58 fill:#438dd5,stroke:#2e6295,color:#ffffff
      59("<div style='font-weight: bold'>App</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go]</div><div style='font-size: 80%; margin-top:10px'>Manage events, data<br />validation and business<br />logic.</div>")
      style 59 fill:#85bbf0,stroke:#5d82a8,color:#000000
      69("<div style='font-weight: bold'>API</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go]</div><div style='font-size: 80%; margin-top:10px'>Manages LPA data validation<br />and draft ingestion</div>")
      style 69 fill:#85bbf0,stroke:#5d82a8,color:#000000
      71("<div style='font-weight: bold'>Case Management Integration API</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go]</div><div style='font-size: 80%; margin-top:10px'>Manages API access for Case<br />Management tasks</div>")
      style 71 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

    59-. "<div>Uses</div><div style='font-size: 70%'></div>" .->58
    59-. "<div>gets LPA Code from</div><div style='font-size: 70%'></div>" .->1
    59-. "<div>writes validated registered<br />data to</div><div style='font-size: 70%'></div>" .->52
    59-. "<div>writes final registered case<br />management data and triggers<br />case working events to</div><div style='font-size: 70%'></div>" .->51
    69-. "<div>Uses</div><div style='font-size: 70%'></div>" .->59
    71-. "<div>Uses</div><div style='font-size: 70%'></div>" .->59
    71-. "<div>allows read access to draft<br />data and write access to<br />executed data</div><div style='font-size: 70%'></div>" .->51
    77-. "<div>makes calls to</div><div style='font-size: 70%'></div>" .->69
    81-. "<div>reads and writes data from</div><div style='font-size: 70%'></div>" .->51
    81-. "<div>writes valid data to</div><div style='font-size: 70%'></div>" .->69
    41-. "<div>makes calls to</div><div style='font-size: 70%'></div>" .->69
  end
