graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [OPG Identity Verification Service - External Identity Services. - Components]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 26 [External Identity Services.]
      style 26 fill:#ffffff,stroke:#5d82a8,color:#5d82a8

      27("<div style='font-weight: bold'>Routing</div><div style='font-size: 70%; margin-top: 0px'>[Component: Go]</div><div style='font-size: 80%; margin-top:10px'>Redirects to appropriate<br />external service, passing<br />back the response.</div>")
      style 27 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

  end
