graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Make a Lasting Power of Attorney Online - System Context]
    style diagram fill:#ffffff,stroke:#ffffff

    12["<div style='font-weight: bold'>Attorney</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Attorney interacting with a<br />Lasting Power of Attorney.</div>"]
    style 12 fill:#08427b,stroke:#052e56,color:#ffffff
    13["<div style='font-weight: bold'>Donor</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Donor drafting the Lasting<br />Power of Attorney.</div>"]
    style 13 fill:#08427b,stroke:#052e56,color:#ffffff
    14["<div style='font-weight: bold'>Certificate Provider</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Certificate Provider<br />interacting with a Lasting<br />Power of Attorney.</div>"]
    style 14 fill:#08427b,stroke:#052e56,color:#ffffff
    16("<div style='font-weight: bold'>OPG Identity Verification Service</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Responsible for verification<br />options on internal and<br />external services.</div>")
    style 16 fill:#1168bd,stroke:#0b4884,color:#ffffff
    40["<div style='font-weight: bold'>Make a Lasting Power of Attorney Online</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Allows users to draft a<br />Lasting Power of Attorney<br />online. [Owner: Modernising,<br />Users: Vega]</div>"]
    style 40 fill:#1168bd,stroke:#0b4884,color:#ffffff
    56("<div style='font-weight: bold'>LPA Drafting Container</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Stores and manages data for<br />pre-registration. [Owner:<br />Modernising, Users: Vega]</div>")
    style 56 fill:#438dd5,stroke:#2e6295,color:#ffffff
    92("<div style='font-weight: bold'>OPG Authentication Service</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>User facing central<br />Authentication service.<br />[Owner: UaLPA, Users:<br />Modernising]</div>")
    style 92 fill:#438dd5,stroke:#2e6295,color:#ffffff

    40-. "<div>authenticates with</div><div style='font-size: 70%'></div>" .->92
    40-. "<div>Uses</div><div style='font-size: 70%'></div>" .->16
    40-. "<div>interacts with</div><div style='font-size: 70%'></div>" .->13
    40-. "<div>interacts with</div><div style='font-size: 70%'></div>" .->12
    40-. "<div>interacts with</div><div style='font-size: 70%'></div>" .->14
    40-. "<div>makes calls to</div><div style='font-size: 70%'></div>" .->56
  end
