@startuml
set separator none
title LPA UID Service - Containers

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<LPAUIDService.APIGateway>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<LPAUIDService.CertificateManager>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<LPAUIDService.DNS>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam database<<LPAUIDService.Database>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
}
skinparam rectangle<<LPAUIDService.IAM>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<LPAUIDService.Lambda>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}

rectangle "LPA UID Service\n<size:10>[Software System]</size>" <<LPAUIDService>> {
  skinparam RectangleBorderColor<<LPAUIDService>> #0b4884
  skinparam RectangleFontColor<<LPAUIDService>> #0b4884

  database "==Database\n<size:10>[Container: DynamoDB]</size>\n\nStores LPA IDs." <<LPAUIDService.Database>> as LPAUIDService.Database
  rectangle "==Lambda\n<size:10>[Container: AWS Lambda, Go]</size>\n\nExecutes code for generating and returning new LPA ID" <<LPAUIDService.Lambda>> as LPAUIDService.Lambda
  rectangle "==IAM\n<size:10>[Container: AWS IAM]</size>\n\nManages permissions to API Gateway" <<LPAUIDService.IAM>> as LPAUIDService.IAM
  rectangle "==Certificate Manager\n<size:10>[Container: AWS Certificate Manager]</size>\n\nGenerate a valid cert for SSL connectivity to the API" <<LPAUIDService.CertificateManager>> as LPAUIDService.CertificateManager
  rectangle "==DNS\n<size:10>[Container: AWS Route 53]</size>\n\nGenerate a friendly DNS Name for the API" <<LPAUIDService.DNS>> as LPAUIDService.DNS
  rectangle "==API Gateway\n<size:10>[Container: AWS API Gateway v2, OpenAPI]</size>\n\nProvides a REST API for communication to the service." <<LPAUIDService.APIGateway>> as LPAUIDService.APIGateway
}

LPAUIDService.APIGateway .[#707070,thickness=2].> LPAUIDService.IAM : "<color:#707070>Validates requests"
LPAUIDService.Lambda .[#707070,thickness=2].> LPAUIDService.Database : "<color:#707070>Queries and writes to"
LPAUIDService.APIGateway .[#707070,thickness=2].> LPAUIDService.Lambda : "<color:#707070>Forwards requests to and Returns responses from"
@enduml