graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [LPA UID Service - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 1 [LPA UID Service]
      style 1 fill:#ffffff,stroke:#0b4884,color:#0b4884

      2[("<div style='font-weight: bold'>Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores LPA UIDs.</div>")]
      style 2 fill:#438dd5,stroke:#2e6295,color:#ffffff
      3("<div style='font-weight: bold'>Lambda</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Lambda, Go]</div><div style='font-size: 80%; margin-top:10px'>Executes code for generating<br />and returning new LPA UID</div>")
      style 3 fill:#85bbf0,stroke:#5d82a8,color:#000000
      5("<div style='font-weight: bold'>IAM</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS IAM]</div><div style='font-size: 80%; margin-top:10px'>Manages permissions to API<br />Gateway</div>")
      style 5 fill:#85bbf0,stroke:#5d82a8,color:#000000
      6("<div style='font-weight: bold'>Certificate Manager</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Certificate Manager]</div><div style='font-size: 80%; margin-top:10px'>Generate a valid cert for SSL<br />connectivity to the API</div>")
      style 6 fill:#85bbf0,stroke:#5d82a8,color:#000000
      7("<div style='font-weight: bold'>DNS</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Route 53]</div><div style='font-size: 80%; margin-top:10px'>Generate a friendly DNS Name<br />for the API</div>")
      style 7 fill:#85bbf0,stroke:#5d82a8,color:#000000
      8("<div style='font-weight: bold'>API Gateway</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS API Gateway v2, OpenAPI]</div><div style='font-size: 80%; margin-top:10px'>Provides a REST API for<br />communication to the service.</div>")
      style 8 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

    8-. "<div>Validates requests</div><div style='font-size: 70%'></div>" .->5
    3-. "<div>Queries and writes to</div><div style='font-size: 70%'></div>" .->2
    8-. "<div>Forwards requests to and<br />Returns responses from</div><div style='font-size: 70%'></div>" .->3
  end
