@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam person<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
person "==Person" <<1>>

skinparam rectangle<<2>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
}
rectangle "==Software System" <<2>>

skinparam rectangle<<3>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
rectangle "==Software System, Component" <<3>>

skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
rectangle "==Software System, Container" <<4>>

skinparam rectangle<<5>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
}
rectangle "==Software System, Existing System" <<5>>

skinparam rectangle<<6>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
rectangle "==Software System, Web Browser" <<6>>

skinparam rectangle<<7>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}
rectangle "==Software System, Web Browser Existing System" <<7>>

rectangle "." <<_transparent>> as 8
8 .[#707070,thickness=2].> 8 : "<color:#707070>Relationship"


@enduml