@startuml
set separator none
title System Landscape

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam person<<Attorney>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<CaseManagementSirius>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5d82a8
  roundCorner 20
}
skinparam rectangle<<CaseManagementPublicAPI>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
}
skinparam person<<CaseWorker>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam person<<CertificateProvider>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam person<<Donor>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<ExternalServices>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
}
skinparam rectangle<<LPADraftingContainer>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
skinparam rectangle<<LPAPaperIngestionService>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
skinparam rectangle<<LPAUIDService>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
}
skinparam rectangle<<MakeaLastingPowerofAttorneyOnline>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<OPGAuthenticationService>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
skinparam rectangle<<OPGInternalPaymentService>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
}
skinparam rectangle<<PublicLPASupportAPI>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
skinparam rectangle<<RegisteredLPADataStore>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
}
skinparam rectangle<<RegisteredLPAService>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
}
skinparam rectangle<<ScanningSoftware>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
  roundCorner 20
}
skinparam person<<ThirdPartySoftware>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<UseanLPA>> {
  BackgroundColor #999999
  FontColor #ffffff
  BorderColor #6b6b6b
}

rectangle "==LPA UID Service\n<size:10>[Software System]</size>\n\nGenerates IDs and stores donor details." <<LPAUIDService>> as LPAUIDService
person "==Third Party Software\n<size:10>[Person]</size>\n\nExternal API software interacting with a Lasting Power of Attorney." <<ThirdPartySoftware>> as ThirdPartySoftware
person "==Attorney\n<size:10>[Person]</size>\n\nAttorney interacting with a Lasting Power of Attorney." <<Attorney>> as Attorney
person "==Donor\n<size:10>[Person]</size>\n\nDonor drafting the Lasting Power of Attorney." <<Donor>> as Donor
person "==Certificate Provider\n<size:10>[Person]</size>\n\nCertificate Provider interacting with a Lasting Power of Attorney." <<CertificateProvider>> as CertificateProvider
person "==Case Worker\n<size:10>[Person]</size>\n\nCase worker." <<CaseWorker>> as CaseWorker
rectangle "==Make a Lasting Power of Attorney Online\n<size:10>[Software System]</size>\n\nAllows users to draft a Lasting Power of Attorney online. [Owner: Modernising, Users: Vega]" <<MakeaLastingPowerofAttorneyOnline>> as MakeaLastingPowerofAttorneyOnline
rectangle "==Case Management Public API\n<size:10>[Software System]</size>\n\nInteraction point between Case Management and other services. [Owner: Vega, Users: UaLPA, Modernising]" <<CaseManagementPublicAPI>> as CaseManagementPublicAPI
rectangle "==Registered LPA Service\n<size:10>[Software System]</size>\n\nHighly available API for reading and searching the LPA Register. [Owner: Vega, Users: UaLPA, Modernising]" <<RegisteredLPAService>> as RegisteredLPAService
rectangle "==LPA Drafting Container\n<size:10>[Software System]</size>\n\nStores and manages data for pre-registration. [Owner: Modernising, Users: Vega]" <<LPADraftingContainer>> as LPADraftingContainer
rectangle "==Registered LPA Data Store\n<size:10>[Software System]</size>\n\nStores immutable LPA data with high availablility, security and auditing. [Owner: Modernising, Users: Vega]" <<RegisteredLPADataStore>> as RegisteredLPADataStore
rectangle "==Public LPA Support API\n<size:10>[Software System]</size>\n\nAllows external companies to add submit LPAs. [Owner: Vega, Users: Modernising]" <<PublicLPASupportAPI>> as PublicLPASupportAPI
rectangle "==LPA Paper Ingestion Service\n<size:10>[Software System]</size>\n\nHandles the ingestion of the Paper Journey and exposes APIs for non valid OCR data for caseworker keying. [Owner: Modernising, Users: Vega]" <<LPAPaperIngestionService>> as LPAPaperIngestionService
rectangle "==OPG Internal Payment Service\n<size:10>[Software System]</size>\n\nHandles GOV.UK Pay and Remissions and Exemptions information between all services and Sirius. [Owner: Vega, Users: Modernising]" <<OPGInternalPaymentService>> as OPGInternalPaymentService
rectangle "==Case Management (Sirius)\n<size:10>[Software System]</size>\n\nCase Management for case working LPAs. [Owner: Vega, Users: Modernising]" <<CaseManagementSirius>> as CaseManagementSirius
rectangle "==OPG Authentication Service\n<size:10>[Software System]</size>\n\nUser facing central Authentication service. [Owner: UaLPA, Users: Modernising]" <<OPGAuthenticationService>> as OPGAuthenticationService
rectangle "==External Services\n<size:10>[Software System]</size>\n\nGOV.UK Notify, Pay, One Login, Yoti, Ordanance Survey" <<ExternalServices>> as ExternalServices
rectangle "==Scanning Software\n<size:10>[Software System]</size>\n\nTBC" <<ScanningSoftware>> as ScanningSoftware
rectangle "==Use an LPA\n<size:10>[Software System]</size>\n\nUse/View an LPA Service. [Owner: UaLPA]" <<UseanLPA>> as UseanLPA

MakeaLastingPowerofAttorneyOnline .[#707070,thickness=2].> Donor : "<color:#707070>interacts with"
MakeaLastingPowerofAttorneyOnline .[#707070,thickness=2].> Attorney : "<color:#707070>interacts with"
MakeaLastingPowerofAttorneyOnline .[#707070,thickness=2].> CertificateProvider : "<color:#707070>interacts with"
LPADraftingContainer .[#707070,thickness=2].> LPAUIDService : "<color:#707070>gets LPA Code from"
LPADraftingContainer .[#707070,thickness=2].> RegisteredLPAService : "<color:#707070>writes validated registered data to"
LPADraftingContainer .[#707070,thickness=2].> CaseManagementPublicAPI : "<color:#707070>writes final registered case management data and triggers case working events to"
PublicLPASupportAPI .[#707070,thickness=2].> LPADraftingContainer : "<color:#707070>makes calls to"
PublicLPASupportAPI .[#707070,thickness=2].> ThirdPartySoftware : "<color:#707070>interacts with"
LPAPaperIngestionService .[#707070,thickness=2].> CaseManagementPublicAPI : "<color:#707070>reads and writes data from"
LPAPaperIngestionService .[#707070,thickness=2].> LPADraftingContainer : "<color:#707070>writes valid data to"
CaseManagementSirius .[#707070,thickness=2].> CaseWorker : "<color:#707070>interacts with"
ScanningSoftware .[#707070,thickness=2].> LPAPaperIngestionService : "<color:#707070>sends scanned LPA Data to"
MakeaLastingPowerofAttorneyOnline .[#707070,thickness=2].> LPADraftingContainer : "<color:#707070>makes calls to"
CaseManagementSirius .[#707070,thickness=2].> LPAUIDService : "<color:#707070>gets LPA Code from"
MakeaLastingPowerofAttorneyOnline .[#707070,thickness=2].> OPGAuthenticationService : "<color:#707070>authenticates with"
UseanLPA .[#707070,thickness=2].> OPGAuthenticationService : "<color:#707070>authenticates with"
UseanLPA .[#707070,thickness=2].> CaseManagementPublicAPI : "<color:#707070>read data from"
UseanLPA .[#707070,thickness=2].> RegisteredLPAService : "<color:#707070>read data from"
RegisteredLPAService .[#707070,thickness=2].> RegisteredLPADataStore : "<color:#707070>writes data to"
CaseManagementSirius .[#707070,thickness=2].> OPGInternalPaymentService : "<color:#707070>writes and read data from"
CaseManagementPublicAPI .[#707070,thickness=2].> CaseManagementSirius : "<color:#707070>writes and read data from"
CaseManagementSirius .[#707070,thickness=2].> RegisteredLPAService : "<color:#707070>reads data from"
@enduml