name: Generate amalgamated package scan report

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '0 19 * * 5'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner-amalgamation@latest
        with:
          organisation_slug: "ministryofjustice"
          organisation_token: ${{ secrets.ORG_ACCESS_TOKEN }}
          team_slug: "opg"
