on:
  workflow_call:
    outputs:
      changes_detected:
        description: "Boolean value for changes detected in /dsl/poas for files"
        value: ${{ jobs.detect_changes_compared_to_main.outputs.changes_detected }}

jobs:
  detect_changes_compared_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Detect changes in /dsl/poas for files compared to main using git diff
        id: detect_changes
        if: github.ref != 'refs/heads/main'
        run: |
          git diff --quiet HEAD origin/main -- dsl/poas && \
          echo "changes=false" >> $GITHUB_OUTPUT || \
          echo "changes=true" >> $GITHUB_OUTPUT
    outputs:
      changes_detected: ${{ steps.detect_changes.outputs.changes }}
