name: Generate package scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Monday, at 6am UTC
    - cron: '0 6 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
