name: Run Reports for [ownership, merges]

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Monday, at 12.15pm
    - cron: '15 12 * * 1'

jobs:
  run_reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        report: ["ownership_report", "merge_report"]
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Checkout reporting repo
      uses: actions/checkout@v2
      with:
        path: opg-repository-reports
        repository: ministryofjustice/opg-repository-reporting
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd opg-repository-reports
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run ownership report
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
      run: |
        cd opg-repository-reports
        python ./${{ matrix.report }}.py --type md --filename ${{ matrix.report }} --exclude opg-webops
        cd -
    - name: Checkout reporting repo
      uses: actions/checkout@v2
      with:
        path: opg-technical-guidance
    - name: Merge report and stubs
      run: |
        stub='./opg-technical-guidance/stubs/${{ matrix.report }}'
        report='./opg-repository-reports/${{ matrix.report }}.md'
        dest='./opg-repository-reports/${{ matrix.report }}.html.md.erb'
        d="${{ steps.date.outputs.date }}"
        python -c "stub = open('${stub}').read().replace('{{date}}','${d}'); report = open('${report}').read(); content = stub.replace('{{report}}', report); open('${dest}', 'w').write(content);"
    - name: Capture the output of the report
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.report }}
        path: opg-repository-reports/${{ matrix.report }}.html.md.erb
