name: "[Python] Run repository reports"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * 1,4'
  workflow_dispatch:
  
jobs:
  run_reports:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        report: ["releases", "software_packages", "stats", "team_metadata"]
    steps:
    - name: Checkout reporting repo
      uses: actions/checkout@v2
      with:
        path: opg-repository-reports
        repository: ministryofjustice/opg-repository-reporting
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd opg-repository-reports/app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run report
      id: reporter
      run: |
        cd opg-repository-reports/app
        python ./${{ matrix.report }}.py --organisation-token="${{ secrets.ORG_ACCESS_TOKEN }}" --organisation-slug="ministryofjustice" --team-slug="opg"
        cd -
    - name: Checkout reporting repo
      uses: actions/checkout@v2
      with:
        path: opg-technical-guidance
    - name: Capture the output of the report
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.report }}
        path: ${{ steps.reporter.outputs.directory }}/
