name: "[Reports] Releases"

on:
  schedule:
    - cron: '0 18 * * 0'
  workflow_dispatch:
  
jobs:
  report:
    name: "Releases"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Releases"
        uses: './.github/actions/generate-report' 
        with:
          name: releases
          script: github_deployment_frequency.py
          args: --duration=6 --org-team="ministryofjustice:opg"
          output: outputs/github_deployment_frequency
          workingdir: ${{ github.workspace }}/_reports_releases
          token: ${{ secrets.ORG_ACCESS_TOKEN }}

