name: "[Reports] Daily Service Uptime"

on:
  pull_request:
    branches: 
      - "main"
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  
jobs:
  report:
    name: "Daily service uptime"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: digideps
            account: ${{ secrets.DIGIDEPS_ACCOUNT_ID }}
          - name: make
            account: ${{ secrets.MAKE_ACCOUNT_ID }}
          - name: modern-lpa
            account: ${{ secrets.MODERN_LPA_ACCOUNT_ID }}
          - name: serve
            account: ${{ secrets.SERVE_ACCOUNT_ID }}
          - name: sirius
            account: ${{ secrets.SIRIUS_ACCOUNT_ID }}
          - name: use
            account: ${{ secrets.USE_ACCOUNT_ID }}
          
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "[${{ matrix.name }}] Daily service uptime"
        uses: './.github/actions/generate-report' 
        with:
          name: "${{ matrix.name }}-daily-uptime"
          script: service_uptime_daily.py
          args: "--service=${{ matrix.name }} --role=arn:aws:iam::${{ matrix.account }}:role/${{ secrets.REPORTING_ROLE }}"
          output: outputs/service_uptime_daily
          workingdir: ${{ github.workspace }}/_reports_service_uptime_daily
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws_region: "eu-west-1"