name: "[Reports] Releases"

on:
  schedule:
    - cron: '0 18 * * 0'
  workflow_dispatch:
  
jobs:
  run_reports:
    name: "Releases"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: 
          - name: releases
            script: github_deployment_frequency.py
            args: --duration=6 --org-team="ministryofjustice:opg"
            output: outputs/github_deployment_frequency
            workingdir: _reports_releases
    steps:
    ## always the same for each part
    - uses: actions/checkout@v4
      with:
        repository: ministryofjustice/opg-dora-metrics
        path: ${{ github.workspace }}/${{ matrix.workingdir }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      working-directory: ${{ github.workspace }}/${{ matrix.workingdir }}
      run: |
        pip install -r requirements.txt
    ## Vary by strat
    - name: "[${{ matrix.name }}] Generate report"
      working-directory: ${{ github.workspace }}/${{ matrix.workingdir }}
      env:      
        GITHUB_ACCESS_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
        LOG_LEVEL: ${{ runner.debug == '1' && 'DEBUG' || 'INFO' }}
        SCRIPT: ${{ matrix.script }}
        ARGS: ${{ matrix.args }}
      run: |
        python ./${{ env.SCRIPT }} ${{ env.ARGS }}
        ls -lart ${{ matrix.output }}
    ## Upload artifact
    - uses: actions/checkout@v4
      with:
        path: opg_technical_guidance
    - name: "[${{ matrix.name }}] Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ github.workspace }}/${{ matrix.workingdir }}/${{ matrix.output }}/
