on:
  workflow_call:
    inputs:
      changes_detected:
        description: 'Boolean value for changes detected in /dsl/poas'
        required: true
        type: string
        default: 'false'

jobs:
  structurizr:
    if: inputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          message: "Render PlantUML files to SVG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
