name: "PR"

on:
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        run: make run-structurizr-export
